services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: unifor_manager
      POSTGRES_USER: unifor
      POSTGRES_PASSWORD: unifor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unifor -d unifor_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24
    command: start --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/unifor_manager
      QUARKUS_DATASOURCE_USERNAME: unifor
      QUARKUS_DATASOURCE_PASSWORD: unifor
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/unifor
      QUARKUS_OIDC_CREDENTIALS_SECRET: 91wTqowfgcNWQp3xEqXfF1YBZhDzbrqk
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    restart: on-failure

volumes:
  postgres_data: {}
